[project]
name = "teleme-chat-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-fasthtml>=0.10.1",
    "ruff>=0.8.2",
]
